#!/bin/bash
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')         
height_dm=$(jq -r '.height' data.json)                  
weight_hg=$(jq -r '.weight' data.json)                  

height_m=$(echo "scale=1; $height_dm / 10" | bc)
weight_kg=$(echo "scale=0; $weight_hg / 10" | bc)
types=$(jq -r '.types[].type.name' data.json | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}' | paste -sd, -)
echo "$name is of type $types, weighs ${weight_kg}kg, and is ${height_m}m tall."
